### ISSUE TITLE
Update install instructions for Python 3.8.x

### ISSUE THREAD

**Issue by sergeyklay** [rybodiddly/Poetry-Pyenv-Homebrew-Numpy-TensorFlow-on-Apple-Silicon-M1#2]
Hello,

As I can see, the provided instruction does not work for Python 3.8.9. Here is an updated one:

```bash
$ PATCH_URL=https://raw.githubusercontent.com/Homebrew/formula-patches/master/python/3.8.7.patch
$ CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include -I$(brew --prefix xz)/include"
$ LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib -L$(brew --prefix xz)/lib"

$ curl -sSL $PATCH_URL | CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" pyenv install --patch 3.8.9

$ unset PATCH_URL CFLAGS LDFLAGS
```

**Comment by rybodiddly** [comment]
Thanks for the update, but please note that some of the module wheels such as scipy included in the release section have been reported to only work with 3.8.6 (because they were built using 3.8.6). With that said, a few of the module wheels can now be natively installed via poetry and no longer require the supplied wheels in the release section. Otherwise you would need to rebuild them using 3.8.9.

**Comment by sergeyklay** [comment]
Hmm.. Good point! Thank you
